# Generated by Django 5.0.6 on 2024-06-24 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goalcategory",
            old_name="id_deleted",
            new_name="is_deleted",
        ),
    ]
